name: Flutter Analyze

on:
  pull_request:
    branches:
      - main

jobs:
  analyze:
    # This job will run on macos virtual machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter

      # Setup Java environment in order to build the Android app.
      #      - name: SETUP | Java
      #        uses: actions/setup-java@v1
      #        with:
      #          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      # Check for any formatting issues in the code.
      - run: flutter format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .
